[package]
name = "path-locator"
version = "0.1.0"
edition = "2021"
description = "A library for finding a file in the parent directory."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
